=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/test_list.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "reference: http://goto/cros-factory-test-list, ./TEST_LIST.md, ./JSON_TEST_LIST.md",
  "definitions": {
    "eval_expression": {
      "type": "string",
      "pattern": "eval! .*",
      "description": "String prefix to indicate this value needs to be evaluated in runtime."
    },
    "eval_boolean": {
      "oneOf":[
        {
          "type": "boolean"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_integer": {
      "oneOf":[
        {
          "type": "integer"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_optional_integer": {
      "oneOf":[
        {
          "type": ["integer", "null"]
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_array": {
      "oneOf":[
        {
          "type": "array"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_object": {
      "oneOf":[
        {
          "type": "object"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "test_comment": {
      "description": "this field will be completely ignored by test list loader.",
      "type": "string"
    },
    "test_object": {
      "type": ["object", "string"],
      "properties": {
        "action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "args": {
          "type": "object"
        },
        "disable_abort": {
          "type": "boolean"
        },
        "disable_services": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dut_options": {
          "type": "object"
        },
        "enable_services": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exclusive_resources": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "iterations": {
          "type": "number"
        },
        "label": {
          "type": ["string", "object"]
        },
        "layout": {
          "$ref": "#/definitions/test_ui_layout"
        },
        "locals": {
          "$ref": "#/definitions/test_constants"
        },
        "no_host": {
          "type": "boolean"
        },
        "allow_reboot": {
          "type": "boolean"
        },
        "parallel": {
          "type": "boolean"
        },
        "pytest_name": {
          "type": "string"
        },
        "retries": {
          "type": "number"
        },
        "run_if": {
          "type": "string"
        },
        "subtests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/test_object"
          }
        },
        "teardown": {
          "type": "boolean"
        },
        "inherit": {
          "type": "string"
        },
        "child_action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "require_run": {
          "type": ["string", "array"],
          "items": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/test_comment"
        }
      },
      "dependencies": {
        "layout": {
          "properties": {
            "parallel": {
              "enum": [true]
            }
          },
          "required": ["parallel"]
        }
      },
      "additionalProperties": false
    },
    "test_allow_list": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "test_phase_allow_list": {
      "type": "object",
      "properties": {
        "PROTO" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "EVT" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "DVT" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "PVT_DOGFOOD" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "PVT" : {
          "$ref": "#/definitions/test_allow_list"
        }
      },
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/test_comment"
        },
        "^[^_].*$": {
          "$ref": "#/definitions/test_allow_list"
        }
      },
      "additionalProperties": false
    },
    "test_options": {
      "__comment": "please see cros.factory.test.test_lists.test_list.Options",
      "type": "object",
      "properties": {
        "auto_run_on_start": {
          "$ref": "#/definitions/eval_boolean",
          "default": true
        },
        "retry_failed_on_start": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "clear_state_on_start": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "auto_run_on_keypress": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "ui_locale": {
          "type": "string",
          "default": "en-US"
        },
        "engineering_password_sha1": {
          "type": ["string", "null"]
        },
        "sync_event_log_period_secs": {
          "$ref": "#/definitions/eval_optional_integer"
        },
        "update_period_secs": {
          "$ref": "#/definitions/eval_optional_integer"
        },
        "stop_on_failure": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "hooks_class": {
          "type": "string",
          "default": "cros.factory.goofy.hooks.Hooks"
        },
        "testlog_hooks": {
          "type": "string",
          "default": "cros.factory.testlog.hooks.Hooks"
        },
        "phase": {
          "oneOf":[
            {
              "enum": ["PROTO", "EVT", "DVT", "PVT_DOGFOOD", "PVT", null]
            },
            {
              "$ref": "#/definitions/eval_expression"
            }
          ]
        },
        "dut_options": {
          "$ref": "#/definitions/eval_object"
        },
        "plugin_config_name": {
          "type": ["string", "null"],
          "default": "goofy_plugin_chromeos"
        },
        "read_device_data_from_vpd_on_init": {
          "$ref": "#/definitions/eval_boolean",
          "default": true
        },
        "skipped_tests": {
          "$ref": "#/definitions/test_phase_allow_list"
        },
        "waived_tests": {
          "$ref": "#/definitions/test_phase_allow_list"
        },
        "conditional_patches": {
          "type": "array",
          "description": "please see cros.factory.test.test_lists.test_list.Options",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "action",
              "conditions"
            ],
            "properties": {
              "action": {
                "enum": ["skip", "waive", "set_retries"],
                "type": "string"
              },
              "args": {
                "type": "object"
              },
              "conditions": {
                "type": "object",
                "required": ["patterns"],
                "additionalProperties": false,
                "properties": {
                  "run_if": {
                    "type": ["string", "array"],
                    "items": {
                      "type": "string"
                    }
                  },
                  "patterns": {
                    "type": ["string", "array"],
                    "items": {
                      "type": "string"
                    }
                  },
                  "phases": {
                    "oneOf":[
                      {
                        "type": "string",
                        "enum": ["PROTO", "EVT", "DVT", "PVT_DOGFOOD", "PVT"]
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "enum": ["PROTO", "EVT", "DVT", "PVT_DOGFOOD", "PVT"]
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/test_comment"
        }
      },
      "additionalProperties": false
    },
    "grt_allow_list": {
      "type": "array",
      "items": {
        "enum": [
          "clear_factory_vpd_entries",
          "clear_gbb_flags",
          "cr50_disable_factory_mode",
          "cr50_finalize",
          "cr50_write_flash_info",
          "gsc_disable_factory_mode",
          "gsc_finalize",
          "gsc_write_flash_info",
          "enable_release_partition",
          "fpmcu_initialize_entropy",
          "generate_stable_device_secret",
          "log_source_hashes",
          "log_system_details",
          "set_fw_bitmap_locale",
          "untar_stateful_files",
          "upload_report",
          "verify_cbi_eeprom_wp_status",
          "verify_cros_config",
          "verify_dlc_images",
          "verify_ec_key",
          "verify_feature_management_flags",
          "verify_fp_key",
          "verify_hwid",
          "verify_keys",
          "verify_me_locked",
          "verify_release_channel",
          "verify_rlz_code",
          "verify_rootfs",
          "verify_switch_wp",
          "verify_system_time",
          "verify_tpm",
          "verify_vpd",
          "verify_sn_bits",
          "wipe_in_place",
          "write_protect"
        ]
      },
      "default": []
    },
    "test_constants": {
      "type": "object",
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "type": "string"
        },
        "^[A-Za-z0-9][A-Za-z0-9_-]*$": {
        }
      },
      "properties": {
        "grt": {
          "type": "object",
          "properties": {
            "force_write_protect": {
              "type": "boolean",
              "description": "*** Write protection is required for mass production and shippable devices. By default we enable write protection starting from PVT stages, but you can start trying write protection earlier by this option.",
              "default": false
            },
            "cbi_eeprom_wp_status": {
              "enum": ["Absent", "Locked", "Unlocked"],
              "description": "Set this to 'Absent' for board without CBI EEPROM. Set this to 'Unlocked' for MLB layouts which requires CBI WP being disabled in pre-PVT and enabled in PVT.",
              "default": "Locked"
            },
            "collect_zero_touch_ids": {
              "type": "boolean",
              "default": false
            },
            "ec_pubkey_path": {
              "type": ["string", "null"],
              "default": null
            },
            "ec_pubkey_hash": {
              "type": ["string", "null"],
              "default": null
            },
            "enable_zero_touch": {
              "type": "boolean",
              "default": false
            },
            "gooftool_skip_list": {
              "$ref": "#/definitions/grt_allow_list"
            },
            "gooftool_waive_list": {
              "$ref": "#/definitions/grt_allow_list"
            },
            "re_sign_release_kernel": {
              "type": "boolean",
              "description": "Enable this if you want to finalize with a DEV signed kernel; go/cros-factory-fw-in-early-builds",
              "default": false
            },
            "secure_wipe": {
              "type": "boolean",
              "default": true
            },
            "is_reference_board": {
              "type": "boolean",
              "default": false
            },
            "project": {
              "type": ["string", "null"],
              "default": null
            },
            "skip_feature_tiering_steps": {
              "type": "boolean",
              "default": false
            },
            "block_dev_mode": {
              "type": "boolean",
              "description": "Enable this if you want to block dev mode with firmware management parameters after finalize. One sample usage can be found in b/243670638.",
              "default": false
            }
          },
          "patternProperties": {
            "^__comment[A-Za-z0-9_-]*$": {
              "$ref": "#/definitions/test_comment"
            }
          },
          "additionalProperties": false
        },
        "overlord": {
          "type": "object",
          "properties": {
            "overlord_urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "tls_no_verify": {
              "type": "boolean"
            }
          }
        },
        "factory_process": {
          "enum": ["FULL", "TWOSTAGES", "RMA"],
          "description": "Set 'FULL' if running a full factory process. Set 'TWOSTAGES' for local OEM project or MLB for RMA. Set 'RMA' if in a RMA center. reference: https://docs.google.com/document/d/15v7O8LWFL_tbTp2X4PKedGZ4IQAP11ZQeKsTJ_eQp1s/preview",
          "default": "FULL"
        }
      },
      "additionalProperties": false
    },
    "test_ui_layout_type": {
      "type": "string",
      "enum": ["tab", "tiled"]
    },
    "test_ui_layout": {
      "anyOf": [
        {
          "$ref": "#/definitions/test_ui_layout_type"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "#/definitions/test_ui_layout_type"
            },
            "options": {
              "type": "object"
            }
          },
          "additionalProperties": false
        }
      ]
    }
  },
  "type": "object",
  "properties": {
    "label": {
      "type": "string"
    },
    "options": {
      "$ref": "#/definitions/test_options"
    },
    "constants": {
      "$ref": "#/definitions/test_constants"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/test_object"
      }
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/test_object"
      }
    },
    "override_args": {
      "__comment": "To override argument of a test in 'tests', maps the test path to a dictionary",
      "type": "object"
    },
    "inherit": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "patternProperties": {
    "^__comment[A-Za-z0-9_-]*$": {
      "$ref": "#/definitions/test_comment"
    }
  },
  "required": [
    "options",
    "constants"
  ],
  "additionalProperties": false
}

=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/generic_fingerprint_examples.test_list.json
{
  "inherit": [
    "generic_fingerprint.test_list"
  ],
  "label": "Generic Fingerprint Sensor Factory tests",
  "constants": {},
  "options": {
    "auto_run_on_start": false
  },
  "definitions": {
    "ElanFPSBaseTest": {
      "inherit": "ElanFPSTest",
      "label": "Elan Fingerprint Sensor Base Test",
      "args": {
        "test_case": 1
      }
    },
    "ElanFPSCompleteTest": {
      "inherit": "ElanFPSTest",
      "label": "Elan Fingerprint Sensor Complete Test",
      "args": {
        "test_case": 15
      }
    },
    "ElanFPSNonInteractiveTest": {
      "inherit": "ElanFPSTest",
      "label": "Elan Fingerprint Sensor Non-interactive Test",
      "args": {
        "test_case": 7
      }
    },
    "ElanFPSResetTest": {
      "inherit": "ElanFPSTest",
      "label": "Elan Fingerprint Sensor Reset Test",
      "args": {
        "test_case": 4
      }
    },
    "ElanFPSSensorTest": {
      "inherit": "ElanFPSTest",
      "label": "Elan Fingerprint Sensor Sensor Test",
      "args": {
        "test_case": 2
      }
    },
    "ElanFPSTestGroup": {
      "inherit": "TestGroup",
      "label": "Elan Fingerprint Sensor Test Group",
      "subtests": [
        "SetHasFingerprint",
        "UnsetHasFingerprint",
        "ProbeFingerprintSensor",
        "UpdateFPFirmware",
        "CheckFPFirmware",
        "UpdateFPFirmwareWithLocalBuildFirmware",
        "ElanFPSBaseTest",
        "ElanFPSSensorTest",
        "ElanFPSResetTest",
        "ElanFPSWOETest",
        "ElanFPSNonInteractiveTest",
        "ElanFPSCompleteTest"
      ]
    },
    "ElanFPSWOETest": {
      "inherit": "ElanFPSTest",
      "label": "Elan Fingerprint Sensor WOE Test",
      "args": {
        "test_case": 8
      }
    },
    "FPSTestPlusManualTest": {
      "inherit": "FPSTest",
      "label": "Fingerprint Sensor test plus manual test",
      "args": {
        "number_of_manual_captures": 10
      }
    },
    "FPSTestPlusPixelMedianTestForBloonchipper": {
      "inherit": "FPSTestPlusPixelMedianTestForDartmonkey",
      "label": "Fingerprint Sensor test plus pixel median test for Bloonchipper",
      "args": {
        "detect_zones": [
          [
            20,
            16,
            27,
            23
          ],
          [
            76,
            16,
            83,
            23
          ],
          [
            132,
            16,
            139,
            23
          ],
          [
            20,
            56,
            27,
            63
          ],
          [
            76,
            56,
            83,
            63
          ],
          [
            132,
            56,
            139,
            63
          ],
          [
            20,
            88,
            27,
            95
          ],
          [
            76,
            88,
            83,
            95
          ],
          [
            132,
            88,
            139,
            95
          ],
          [
            20,
            128,
            27,
            135
          ],
          [
            76,
            128,
            83,
            135
          ],
          [
            132,
            128,
            139,
            135
          ]
        ]
      }
    },
    "FPSTestPlusPixelMedianTestForDartmonkey": {
      "inherit": "FPSTest",
      "label": "Fingerprint Sensor test plus pixel median test for Dartmonkey",
      "args": {
        "max_dead_pixels": 10,
        "pixel_median": {
          "cb_type1": [
            180,
            220
          ],
          "cb_type2": [
            80,
            120
          ],
          "icb_type1": [
            15,
            70
          ],
          "icb_type2": [
            155,
            210
          ]
        },
        "detect_zones": [
          [
            8,
            16,
            15,
            23
          ],
          [
            24,
            16,
            31,
            23
          ],
          [
            40,
            16,
            47,
            23
          ],
          [
            8,
            66,
            15,
            73
          ],
          [
            24,
            66,
            31,
            73
          ],
          [
            40,
            66,
            47,
            73
          ],
          [
            8,
            118,
            15,
            125
          ],
          [
            24,
            118,
            31,
            125
          ],
          [
            40,
            118,
            47,
            125
          ],
          [
            8,
            168,
            15,
            175
          ],
          [
            24,
            168,
            31,
            175
          ],
          [
            40,
            168,
            47,
            175
          ]
        ]
      }
    },
    "FPSTestPlusRubberStamperTest": {
      "inherit": "FPSTest",
      "label": "Fingerprint Sensor test plus rubber stamper test",
      "args": {
        "rubber_finger_present": true
      }
    },
    "FingerprintTests": {
      "inherit": "TestGroup",
      "subtests": [
        "SetHasFingerprint",
        "UnsetHasFingerprint",
        "ProbeFingerprintSensor",
        "UpdateFPFirmware",
        "CheckFPFirmware",
        "UpdateFPFirmwareWithLocalBuildFirmware",
        "FPSTest",
        "FPSTestPlusManualTest",
        "FPSTestPlusPixelMedianTestForDartmonkey",
        "FPSTestPlusPixelMedianTestForBloonchipper",
        "FPSTestPlusRubberStamperTest",
        "FPSGroup"
      ]
    },
    "ProbeFingerprintSensor": {
      "pytest_name": "probe.probe",
      "label": "Probe Fingerprint Sensor",
      "args": {
        "component_list": [
          "fingerprint"
        ],
        "config_file": "/usr/local/factory/py/hwid/v3/default_probe_statement.json",
        "overridden_rules": [
          [
            "fingerprint",
            "==",
            1
          ]
        ]
      }
    },
    "SetHasFingerprint": {
      "pytest_name": "exec_shell",
      "label": "Set Has Fingerprint",
      "related_components": [
        "test_tags.TestCategory.FINGERPRINT_SENSOR"
      ],
      "args": {
        "commands": "factory device-data component.has_fingerprint=1"
      }
    },
    "UnsetHasFingerprint": {
      "pytest_name": "exec_shell",
      "label": "Unset Has Fingerprint",
      "related_components": [
        "test_tags.TestCategory.FINGERPRINT_SENSOR"
      ],
      "args": {
        "commands": "factory device-data component.has_fingerprint=0"
      }
    },
    "UpdateFPFirmwareWithLocalBuildFirmware": {
      "pytest_name": "update_fpmcu_firmware",
      "label": "Update Fingerprint Firmware with Local Build Firmware",
      "args": {
        "method": "UPDATE",
        "firmware_file": "/path/to/image.bin"
      }
    }
  },
  "tests": [
    "FingerprintTests",
    "ElanFPSTestGroup"
  ]
}

=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/generic_fingerprint.test_list.json
{
  "inherit": [
    "base.test_list"
  ],
  "constants": {},
  "options": {},
  "definitions": {
    "CheckFPFirmware": {
      "pytest_name": "update_fpmcu_firmware",
      "label": "Check Fingerprint Firmware",
      "run_if": "device.component.has_fingerprint",
      "args": {
        "method": "CHECK_VERSION"
      }
    },
    "ElanFPSTest": {
      "pytest_name": "fingerprint_sensor_elan",
      "label": "Elan Fingerprint Sensor Test",
      "run_if": "device.component.has_fingerprint and device.component.fingerprint_board == 'buccaneer'",
      "args": {
        "fpmode_retry_count": 2
      }
    },
    "FPSGroup": {
      "label": "Fingerprint Test Group",
      "run_if": "device.component.has_fingerprint",
      "subtests": [
        "UpdateFPFirmware",
        "RebootStep",
        "CheckFPFirmware",
        "ElanFPSTest",
        "FPSTest"
      ]
    },
    "FPSTest": {
      "pytest_name": "fingerprint_sensor_fpc",
      "label": "Fingerprint Sensor test",
      "run_if": "device.component.has_fingerprint",
      "args": {
        "fpframe_retry_count": 2
      }
    },
    "UpdateFPFirmware": {
      "pytest_name": "update_fpmcu_firmware",
      "label": "Update Fingerprint Firmware",
      "run_if": "device.component.has_fingerprint"
    }
  }
}

=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/generic_camera_examples.test_list.json
{
  "inherit": [
    "generic_camera.test_list"
  ],
  "label": "Generic Camera Factory tests",
  "constants": {},
  "options": {
    "auto_run_on_start": false
  },
  "definitions": {
    "CameraTests": {
      "inherit": "TestGroup",
      "subtests": [
        "ProbeCamera",
        "FrontCameraAssemble",
        "FrontCameraAssembleQR",
        "FrontCameraFace",
        "FrontCameraLED",
        "FrontCameraManual",
        "FrontCameraManualOpenCV",
        "FrontCameraQRScan",
        "RearCameraAssemble",
        "RearCameraAssembleQR",
        "RearCameraFace",
        "RearCameraLED",
        "RearCameraManual",
        "RearCameraManualOpenCV",
        "RearCameraQRScan",
        "CameraNoCharacteristics",
        "FrontCameraAssemble07",
        "FrontCameraQRScan1920x1080",
        "FrontCameraStress",
        "FrontCameraFrames",
        "FrontCameraBrightness"
      ]
    },
    "FrontCameraAssemble07": {
      "inherit": "FrontCameraAssemble",
      "label": "Front Camera Assemble 07",
      "args": {
        "min_luminance_ratio": 0.7
      }
    },
    "FrontCameraBrightness": {
      "inherit": "FrontCamera",
      "label": "Front Camera Brightness",
      "args": {
        "num_frames_to_pass": 5,
        "mode": "brightness",
        "timeout_secs": 3,
        "brightness_range": [
          null,
          10
        ]
      }
    },
    "FrontCameraFrames": {
      "inherit": "FrontCamera",
      "label": "Front Camera Frames",
      "args": {
        "num_frames_to_pass": 100,
        "mode": "frame_count",
        "timeout_secs": 1000,
        "show_image": false
      }
    },
    "FrontCameraManualOpenCV": {
      "inherit": "FrontCameraManual",
      "label": "Front Camera Manual OpenCV",
      "args": {
        "e2e_mode": false
      }
    },
    "FrontCameraQRScan1920x1080": {
      "inherit": "FrontCameraQRScan",
      "label": "Front Camera QR Scan 1920x1080",
      "args": {
        "camera_args": {
          "resolution": [
            1920,
            1080
          ]
        }
      }
    },
    "FrontCameraStress": {
      "inherit": "FrontCamera",
      "label": "Front Camera Stress",
      "args": {
        "mode": "timeout",
        "timeout_secs": 1000,
        "show_image": false
      }
    },
    "RearCameraManualOpenCV": {
      "inherit": "RearCameraManual",
      "label": "Rear Camera Manual OpenCV",
      "args": {
        "e2e_mode": false
      }
    }
  },
  "tests": [
    "CameraTests"
  ]
}
