=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/test_list.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "reference: http://goto/cros-factory-test-list, ./TEST_LIST.md, ./JSON_TEST_LIST.md",
  "definitions": {
    "eval_expression": {
      "type": "string",
      "pattern": "eval! .*",
      "description": "String prefix to indicate this value needs to be evaluated in runtime."
    },
    "eval_boolean": {
      "oneOf":[
        {
          "type": "boolean"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_integer": {
      "oneOf":[
        {
          "type": "integer"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_optional_integer": {
      "oneOf":[
        {
          "type": ["integer", "null"]
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_array": {
      "oneOf":[
        {
          "type": "array"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "eval_object": {
      "oneOf":[
        {
          "type": "object"
        },
        {
          "$ref": "#/definitions/eval_expression"
        }
      ]
    },
    "test_comment": {
      "description": "this field will be completely ignored by test list loader.",
      "type": "string"
    },
    "test_object": {
      "type": ["object", "string"],
      "properties": {
        "action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "args": {
          "type": "object"
        },
        "disable_abort": {
          "type": "boolean"
        },
        "disable_services": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dut_options": {
          "type": "object"
        },
        "enable_services": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exclusive_resources": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "iterations": {
          "type": "number"
        },
        "label": {
          "type": ["string", "object"]
        },
        "layout": {
          "$ref": "#/definitions/test_ui_layout"
        },
        "locals": {
          "$ref": "#/definitions/test_constants"
        },
        "no_host": {
          "type": "boolean"
        },
        "allow_reboot": {
          "type": "boolean"
        },
        "parallel": {
          "type": "boolean"
        },
        "pytest_name": {
          "type": "string"
        },
        "retries": {
          "type": "number"
        },
        "run_if": {
          "type": "string"
        },
        "subtests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/test_object"
          }
        },
        "teardown": {
          "type": "boolean"
        },
        "inherit": {
          "type": "string"
        },
        "child_action_on_failure": {
          "type": "string",
          "enum": ["NEXT", "PARENT", "STOP"]
        },
        "require_run": {
          "type": ["string", "array"],
          "items": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/test_comment"
        }
      },
      "dependencies": {
        "layout": {
          "properties": {
            "parallel": {
              "enum": [true]
            }
          },
          "required": ["parallel"]
        }
      },
      "additionalProperties": false
    },
    "test_allow_list": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "test_phase_allow_list": {
      "type": "object",
      "properties": {
        "PROTO" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "EVT" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "DVT" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "PVT_DOGFOOD" : {
          "$ref": "#/definitions/test_allow_list"
        },
        "PVT" : {
          "$ref": "#/definitions/test_allow_list"
        }
      },
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/test_comment"
        },
        "^[^_].*$": {
          "$ref": "#/definitions/test_allow_list"
        }
      },
      "additionalProperties": false
    },
    "test_options": {
      "__comment": "please see cros.factory.test.test_lists.test_list.Options",
      "type": "object",
      "properties": {
        "auto_run_on_start": {
          "$ref": "#/definitions/eval_boolean",
          "default": true
        },
        "retry_failed_on_start": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "clear_state_on_start": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "auto_run_on_keypress": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "ui_locale": {
          "type": "string",
          "default": "en-US"
        },
        "engineering_password_sha1": {
          "type": ["string", "null"]
        },
        "sync_event_log_period_secs": {
          "$ref": "#/definitions/eval_optional_integer"
        },
        "update_period_secs": {
          "$ref": "#/definitions/eval_optional_integer"
        },
        "stop_on_failure": {
          "$ref": "#/definitions/eval_boolean",
          "default": false
        },
        "hooks_class": {
          "type": "string",
          "default": "cros.factory.goofy.hooks.Hooks"
        },
        "testlog_hooks": {
          "type": "string",
          "default": "cros.factory.testlog.hooks.Hooks"
        },
        "phase": {
          "oneOf":[
            {
              "enum": ["PROTO", "EVT", "DVT", "PVT_DOGFOOD", "PVT", null]
            },
            {
              "$ref": "#/definitions/eval_expression"
            }
          ]
        },
        "dut_options": {
          "$ref": "#/definitions/eval_object"
        },
        "plugin_config_name": {
          "type": ["string", "null"],
          "default": "goofy_plugin_chromeos"
        },
        "read_device_data_from_vpd_on_init": {
          "$ref": "#/definitions/eval_boolean",
          "default": true
        },
        "skipped_tests": {
          "$ref": "#/definitions/test_phase_allow_list"
        },
        "waived_tests": {
          "$ref": "#/definitions/test_phase_allow_list"
        },
        "conditional_patches": {
          "type": "array",
          "description": "please see cros.factory.test.test_lists.test_list.Options",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "action",
              "conditions"
            ],
            "properties": {
              "action": {
                "enum": ["skip", "waive", "set_retries"],
                "type": "string"
              },
              "args": {
                "type": "object"
              },
              "conditions": {
                "type": "object",
                "required": ["patterns"],
                "additionalProperties": false,
                "properties": {
                  "run_if": {
                    "type": ["string", "array"],
                    "items": {
                      "type": "string"
                    }
                  },
                  "patterns": {
                    "type": ["string", "array"],
                    "items": {
                      "type": "string"
                    }
                  },
                  "phases": {
                    "oneOf":[
                      {
                        "type": "string",
                        "enum": ["PROTO", "EVT", "DVT", "PVT_DOGFOOD", "PVT"]
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "enum": ["PROTO", "EVT", "DVT", "PVT_DOGFOOD", "PVT"]
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/test_comment"
        }
      },
      "additionalProperties": false
    },
    "grt_allow_list": {
      "type": "array",
      "items": {
        "enum": [
          "clear_factory_vpd_entries",
          "clear_gbb_flags",
          "cr50_disable_factory_mode",
          "cr50_finalize",
          "cr50_write_flash_info",
          "gsc_disable_factory_mode",
          "gsc_finalize",
          "gsc_write_flash_info",
          "enable_release_partition",
          "fpmcu_initialize_entropy",
          "generate_stable_device_secret",
          "log_source_hashes",
          "log_system_details",
          "set_fw_bitmap_locale",
          "untar_stateful_files",
          "upload_report",
          "verify_cbi_eeprom_wp_status",
          "verify_cros_config",
          "verify_dlc_images",
          "verify_ec_key",
          "verify_feature_management_flags",
          "verify_fp_key",
          "verify_hwid",
          "verify_keys",
          "verify_me_locked",
          "verify_release_channel",
          "verify_rlz_code",
          "verify_rootfs",
          "verify_switch_wp",
          "verify_system_time",
          "verify_tpm",
          "verify_vpd",
          "verify_sn_bits",
          "wipe_in_place",
          "write_protect"
        ]
      },
      "default": []
    },
    "test_constants": {
      "type": "object",
      "patternProperties": {
        "^__comment[A-Za-z0-9_-]*$": {
          "type": "string"
        },
        "^[A-Za-z0-9][A-Za-z0-9_-]*$": {
        }
      },
      "properties": {
        "grt": {
          "type": "object",
          "properties": {
            "force_write_protect": {
              "type": "boolean",
              "description": "*** Write protection is required for mass production and shippable devices. By default we enable write protection starting from PVT stages, but you can start trying write protection earlier by this option.",
              "default": false
            },
            "cbi_eeprom_wp_status": {
              "enum": ["Absent", "Locked", "Unlocked"],
              "description": "Set this to 'Absent' for board without CBI EEPROM. Set this to 'Unlocked' for MLB layouts which requires CBI WP being disabled in pre-PVT and enabled in PVT.",
              "default": "Locked"
            },
            "collect_zero_touch_ids": {
              "type": "boolean",
              "default": false
            },
            "ec_pubkey_path": {
              "type": ["string", "null"],
              "default": null
            },
            "ec_pubkey_hash": {
              "type": ["string", "null"],
              "default": null
            },
            "enable_zero_touch": {
              "type": "boolean",
              "default": false
            },
            "gooftool_skip_list": {
              "$ref": "#/definitions/grt_allow_list"
            },
            "gooftool_waive_list": {
              "$ref": "#/definitions/grt_allow_list"
            },
            "re_sign_release_kernel": {
              "type": "boolean",
              "description": "Enable this if you want to finalize with a DEV signed kernel; go/cros-factory-fw-in-early-builds",
              "default": false
            },
            "secure_wipe": {
              "type": "boolean",
              "default": true
            },
            "is_reference_board": {
              "type": "boolean",
              "default": false
            },
            "project": {
              "type": ["string", "null"],
              "default": null
            },
            "skip_feature_tiering_steps": {
              "type": "boolean",
              "default": false
            },
            "block_dev_mode": {
              "type": "boolean",
              "description": "Enable this if you want to block dev mode with firmware management parameters after finalize. One sample usage can be found in b/243670638.",
              "default": false
            }
          },
          "patternProperties": {
            "^__comment[A-Za-z0-9_-]*$": {
              "$ref": "#/definitions/test_comment"
            }
          },
          "additionalProperties": false
        },
        "overlord": {
          "type": "object",
          "properties": {
            "overlord_urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "tls_no_verify": {
              "type": "boolean"
            }
          }
        },
        "factory_process": {
          "enum": ["FULL", "TWOSTAGES", "RMA"],
          "description": "Set 'FULL' if running a full factory process. Set 'TWOSTAGES' for local OEM project or MLB for RMA. Set 'RMA' if in a RMA center. reference: https://docs.google.com/document/d/15v7O8LWFL_tbTp2X4PKedGZ4IQAP11ZQeKsTJ_eQp1s/preview",
          "default": "FULL"
        }
      },
      "additionalProperties": false
    },
    "test_ui_layout_type": {
      "type": "string",
      "enum": ["tab", "tiled"]
    },
    "test_ui_layout": {
      "anyOf": [
        {
          "$ref": "#/definitions/test_ui_layout_type"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "#/definitions/test_ui_layout_type"
            },
            "options": {
              "type": "object"
            }
          },
          "additionalProperties": false
        }
      ]
    }
  },
  "type": "object",
  "properties": {
    "label": {
      "type": "string"
    },
    "options": {
      "$ref": "#/definitions/test_options"
    },
    "constants": {
      "$ref": "#/definitions/test_constants"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/test_object"
      }
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/test_object"
      }
    },
    "override_args": {
      "__comment": "To override argument of a test in 'tests', maps the test path to a dictionary",
      "type": "object"
    },
    "inherit": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "patternProperties": {
    "^__comment[A-Za-z0-9_-]*$": {
      "$ref": "#/definitions/test_comment"
    }
  },
  "required": [
    "options",
    "constants"
  ],
  "additionalProperties": false
}

=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/generic_camera.test_list.json
{
  "inherit": [
    "generic_common.test_list"
  ],
  "constants": {
    "__comment": "has_device_data is defined in generic_common."
  },
  "options": {},
  "definitions": {
    "Camera": {
      "pytest_name": "camera",
      "__comment": "This test object cannot be run directly. User have to inherit and modify it."
    },
    "CameraManual": {
      "inherit": "Camera",
      "__comment": "This test object cannot be run directly. User have to inherit and modify it.",
      "args": {
        "mode": "manual"
      }
    },
    "CameraNoCharacteristics": {
      "pytest_name": "camera",
      "label": "Camera without camera_characteristics.conf",
      "__comment": "This is used if camera_characteristics.conf is not ready. Users must replace ``camera_usb_vid_pid`` with vid pid they are testing.",
      "args": {
        "mode": "manual",
        "e2e_mode": false,
        "camera_facing": null,
        "camera_usb_vid_pid": [
          "13d3",
          "56ec"
        ]
      }
    },
    "CameraTests": {
      "label": "Camera Tests",
      "subtests": [
        "FrontCamera",
        "FrontCameraLED",
        "RearCamera",
        "RearCameraLED"
      ]
    },
    "FrontCamera": {
      "inherit": "Camera",
      "label": "Front Camera",
      "run_if": "not constants.has_device_data or device.component.has_front_camera",
      "args": {
        "camera_facing": "front"
      }
    },
    "FrontCameraAssemble": {
      "inherit": "FrontCamera",
      "label": "Front Camera Assemble",
      "args": {
        "mode": "camera_assemble",
        "min_luminance_ratio": 0.5
      }
    },
    "FrontCameraAssembleQR": {
      "inherit": "FrontCamera",
      "label": "Front Camera Assemble QR",
      "args": {
        "mode": "camera_assemble_qr",
        "min_luminance_ratio": 0.5,
        "QR_string": "ChromeTeam"
      }
    },
    "FrontCameraFace": {
      "inherit": "FrontCamera",
      "label": "Front Camera Face",
      "args": {
        "mode": "face"
      }
    },
    "FrontCameraLED": {
      "inherit": "FrontCamera",
      "label": "Front Camera LED",
      "args": {
        "mode": "manual_led"
      }
    },
    "FrontCameraManual": {
      "inherit": "FrontCamera",
      "label": "Front Camera Manual",
      "args": {
        "mode": "manual"
      }
    },
    "FrontCameraQRScan": {
      "inherit": "FrontCamera",
      "label": "Front Camera QR Scan",
      "args": {
        "mode": "qr",
        "QR_string": "ChromeTeam",
        "timeout_secs": 2000
      }
    },
    "ProbeCamera": {
      "pytest_name": "probe.probe",
      "label": "Probe Camera",
      "args": {
        "component_list": [
          "camera"
        ],
        "config_file": "/usr/local/factory/py/hwid/v3/default_probe_statement.json",
        "overridden_rules": [
          [
            "camera",
            "==",
            2
          ]
        ]
      }
    },
    "QRScan": {
      "inherit": "Camera",
      "label": "QR Scan",
      "__comment": "Deprecated. Use FrontCameraQRScan or RearCameraQRScan.",
      "args": {
        "mode": "qr",
        "QR_string": "Hello ChromeOS!"
      }
    },
    "RearCamera": {
      "inherit": "Camera",
      "label": "Rear Camera",
      "run_if": "not constants.has_device_data or device.component.has_rear_camera",
      "args": {
        "camera_facing": "rear"
      }
    },
    "RearCameraAssemble": {
      "inherit": "RearCamera",
      "label": "Rear Camera Assemble",
      "args": {
        "mode": "camera_assemble",
        "min_luminance_ratio": 0.5
      }
    },
    "RearCameraAssembleQR": {
      "inherit": "RearCamera",
      "label": "Rear Camera Assemble QR",
      "args": {
        "mode": "camera_assemble_qr",
        "min_luminance_ratio": 0.5,
        "QR_string": "ChromeTeam"
      }
    },
    "RearCameraFace": {
      "inherit": "RearCamera",
      "label": "Rear Camera Face",
      "args": {
        "mode": "face"
      }
    },
    "RearCameraLED": {
      "inherit": "RearCamera",
      "label": "Rear Camera LED",
      "args": {
        "mode": "manual_led"
      }
    },
    "RearCameraManual": {
      "inherit": "RearCamera",
      "label": "Rear Camera Manual",
      "args": {
        "mode": "manual"
      }
    },
    "RearCameraQRScan": {
      "inherit": "RearCamera",
      "label": "Rear Camera QR Scan",
      "args": {
        "mode": "qr",
        "QR_string": "ChromeTeam",
        "timeout_secs": 2000
      }
    }
  }
}

=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/main_readiness.test_list.json
{
  "inherit": [
    "generic_audio_examples.test_list",
    "generic_battery_examples.test_list",
    "generic_camera_examples.test_list",
    "generic_cellular_examples.test_list",
    "generic_display_panel_examples.test_list",
    "generic_dram_examples.test_list",
    "generic_ec_component_accel_examples.test_list",
    "generic_ec_component_als_examples.test_list",
    "generic_ethernet_examples.test_list",
    "generic_fingerprint_examples.test_list",
    "generic_storage_examples.test_list",
    "generic_touchpad_examples.test_list",
    "generic_touchscreen_examples.test_list",
    "generic_tpm_examples.test_list",
    "generic_wireless_examples.test_list",
    "generic_common.test_list"
  ],
  "label": "Main Readiness Factory tests",
  "constants": {},
  "options": {
    "auto_run_on_start": false
  },
  "definitions": {
    "MiscellaneousHWTests": {
      "inherit": "TestGroup",
      "subtests": [
        "Keyboard",
        "HWButton",
        "Fan",
        "ThermalSensors"
      ]
    }
  },
  "tests": [
    "AccelerometerIMUTests",
    "AmbientLightSensorTests",
    "AudioTests",
    "BatteryTests",
    "CameraTests",
    "CellularTests",
    "DRAMTests",
    "DisplayPanelTests",
    "EthernetTests",
    "FingerprintTests",
    "FPCFPSTests",
    "StorageTests",
    "TouchscreenTests",
    "TouchpadTests",
    "TPMTests",
    "WirelessTests",
    "MiscellaneousHWTests"
  ]
}

=== chromium-full-mirror/chromiumos_platform_factory/py/test/test_lists/generic_rrt.test_list.json
{
  "inherit": [
    "generic_camera.test_list",
    "generic_common.test_list"
  ],
  "label": "Generic Rolling Reliability",
  "constants": {
    "rrt": {
      "sat_duration_secs": 28800,
      "dozing_sat_duration_secs": 600
    }
  },
  "options": {
    "ui_locale": "zh-CN"
  },
  "definitions": {
    "RRTCountdown": {
      "pytest_name": "countdown",
      "__comment": "temp_criteria: A list of rules to check that temperature is under the given range, rule format is [name, temp_index, warning_temp, critical_temp]",
      "args": {
        "log_interval": 10,
        "grace_secs": 480,
        "temp_max_delta": 10,
        "temp_criteria": [
          [
            "CPU",
            null,
            90,
            100
          ]
        ]
      }
    },
    "RRTDozingStress": {
      "label": "Dozing Stress",
      "parallel": true,
      "subtests": [
        {
          "inherit": "StressAppTest",
          "args": {
            "seconds": "eval! constants.rrt.dozing_sat_duration_secs",
            "free_memory_only": true,
            "wait_secs": 60
          }
        },
        {
          "inherit": "SuspendResume",
          "retries": 2,
          "args": {
            "cycles": 15,
            "suspend_delay_min_secs": 28,
            "suspend_delay_max_secs": 30,
            "suspend_time_margin_min_secs": -1
          }
        },
        {
          "inherit": "RRTCountdown",
          "args": {
            "duration_secs": "eval! constants.rrt.dozing_sat_duration_secs"
          }
        }
      ]
    },
    "RRTRebootCheck": {
      "inherit": "FlattenGroup",
      "subtests": [
        {
          "inherit": "ExecShell",
          "label": "Check WLAN",
          "args": {
            "commands": "ifconfig wlan0"
          }
        },
        {
          "inherit": "ExecShell",
          "label": "Check Bluetooth",
          "args": {
            "commands": "hciconfig hci0"
          }
        }
      ]
    },
    "RRTStressGroup": {
      "label": "Stress Group",
      "parallel": true,
      "subtests": [
        {
          "inherit": "WebGLAquarium",
          "args": {
            "duration_secs": "eval! constants.rrt.sat_duration_secs"
          }
        },
        {
          "inherit": "Camera",
          "args": {
            "mode": "timeout",
            "timeout_secs": "eval! constants.rrt.sat_duration_secs",
            "show_image": false
          }
        },
        {
          "inherit": "URandom",
          "args": {
            "duration_secs": "eval! constants.rrt.sat_duration_secs"
          }
        },
        {
          "inherit": "StressAppTest",
          "args": {
            "seconds": "eval! constants.rrt.sat_duration_secs",
            "free_memory_only": true,
            "wait_secs": 60
          }
        },
        {
          "inherit": "RRTCountdown",
          "args": {
            "duration_secs": "eval! constants.rrt.sat_duration_secs"
          }
        }
      ]
    },
    "RRTWarmColdReboot": {
      "inherit": "TestGroup",
      "label": "Warm Cold Reboot",
      "subtests": [
        "ColdReset",
        "RRTRebootCheck",
        "Barrier",
        {
          "inherit": "Idle",
          "args": {
            "wait_secs": 60
          }
        },
        "RebootStep",
        "RRTRebootCheck",
        "Barrier"
      ]
    }
  },
  "tests": [
    {
      "inherit": "Start",
      "args": {
        "require_external_power": true
      }
    },
    {
      "inherit": "RebootStep",
      "iterations": 1500
    },
    {
      "inherit": "RRTWarmColdReboot",
      "iterations": 50
    },
    {
      "inherit": "TestGroup",
      "label": "RRT",
      "iterations": 21,
      "subtests": [
        "RRTStressGroup",
        "Barrier",
        "RebootStep",
        "RRTDozingStress",
        "Barrier",
        {
          "inherit": "RebootStep",
          "iterations": 15
        },
        "ColdReset",
        "Barrier"
      ]
    }
  ]
}
